export const bookAbbreviations = {
    "Génesis": "Gn",
    "Éxodo": "Ex",
    "Levítico": "Lv",
    "Números": "Nm",
    "Deuteronomio": "Dt",
    "Josué": "Jos",
    "Jueces": "Jue",
    "Rut": "Rt",
    "1 Samuel": "1 Sm",
    "2 Samuel": "2 Sm",
    "1 Reyes": "1 Re",
    "2 Reyes": "2 Re",
    "1 Crónicas": "1 Cr",
    "2 Crónicas": "2 Cr",
    "Esdras": "Esd",
    "Nehemías": "Neh",
    "Tobías": "Tob",
    "Judit": "Jdt",
    "Ester": "Est",
    "1 Macabeos": "1 Mac",
    "2 Macabeos": "2 Mac",
    "Job": "Job",
    "Salmos": "Sal",
    "Proverbios": "Prov",
    "Eclesiastés": "Ecl",
    "Cantar de los Cantares": "Cant",
    "Sabiduría": "Sab",
    "Eclesiástico": "Eclo",
    "Isaías": "Is",
    "Jeremías": "Jer",
    "Lamentaciones": "Lam",
    "Baruc": "Bar",
    "Ezequiel": "Ez",
    "Daniel": "Dan",
    "Oseas": "Os",
    "Joel": "Jl",
    "Amós": "Am",
    "Abdías": "Abd",
    "Jonás": "Jon",
    "Miqueas": "Miq",
    "Nahúm": "Nah",
    "Habacuc": "Hab",
    "Sofonías": "Sof",
    "Hageo": "Ag",
    "Zacarías": "Zac",
    "Malaquías": "Mal",
    "Mateo": "Mt",
    "Marcos": "Mc",
    "Lucas": "Lc",
    "Juan": "Jn",
    "Hechos de los Apóstoles": "Hch",
    "Hechos": "Hch",
    "Romanos": "Rom",
    "1 Corintios": "1 Cor",
    "2 Corintios": "2 Cor",
    "Gálatas": "Gal",
    "Efesios": "Ef",
    "Filipenses": "Flp",
    "Colosenses": "Col",
    "1 Tesalonicenses": "1 Tes",
    "2 Tesalonicenses": "2 Tes",
    "1 Timoteo": "1 Tim",
    "2 Timoteo": "2 Tim",
    "Tito": "Tit",
    "Filemón": "Flm",
    "Hebreos": "Heb",
    "Santiago": "Sant",
    "1 Pedro": "1 Pe",
    "2 Pedro": "2 Pe",
    "1 Juan": "1 Jn",
    "2 Juan": "2 Jn",
    "3 Juan": "3 Jn",
    "Judas": "Jds",
    "Apocalipsis": "Ap"
};

export const getAbbreviation = (bookName) => {
    // Normalize input: remove accents for flexible matching if needed, but map keys have accents
    // Try direct match first
    if (bookAbbreviations[bookName]) return bookAbbreviations[bookName];

    // Try case insensitive
    const key = Object.keys(bookAbbreviations).find(k => k.toLowerCase() === bookName.toLowerCase());
    if (key) return bookAbbreviations[key];

    // Fallback: return first 3 chars
    return bookName.substring(0, 3);
};
